// Generated by scripts/export-sprite-sheets.py — do not edit by hand.
import type { CompanionId } from "@/features/pokeden/companions";

// Source provenance (sheet -> .aseprite source; several sources are cross-named):
//   squirtle-sheet.png <- blastoise/squirtle.aseprite
//   wartortle-sheet.png <- blastoise/wartortle.aseprite
//   blastoise-sheet.png <- blastoise/blastoise.aseprite
//   bulbasaur-sheet.png <- bulbasaur/ivysaur.aseprite // cross-named: holds Bulbasaur art
//   ivysaur-sheet.png <- bulbasaur/venosaur.aseprite // cross-named: holds Ivysaur art
//   venusaur-sheet.png <- bulbasaur/bulbasaur.aseprite // cross-named: holds Venusaur art
//   charmander-sheet.png <- charizard/charmander.aseprite
//   charmeleon-sheet.png <- charizard/charmeleon.aseprite
//   charizard-sheet.png <- charizard/charizard.aseprite
//   gastly-sheet.png <- gengar/gastly.aseprite
//   haunter-sheet.png <- gengar/haunter.aseprite
//   munchlax-sheet.png <- snorlax/munchlax.aseprite
//   snorlax-sheet.png <- snorlax/snorlax.aseprite
//   jigglypuff-sheet.png <- wigglypuff/jigglypuff.aseprite
//   wigglytuff-sheet.png <- wigglypuff/wigglypuff.aseprite // cross-named: holds Wigglytuff art
//   totodile-sheet.png <- totodile/totodile.aseprite
//   croconow-sheet.png <- totodile/croconow.aseprite
//   feraligatr-sheet.png <- totodile/feraligatr.aseprite
//   pikachu-sheet.png <- pickachu/pickachu.aseprite // cross-named: holds Pikachu art
//   raichu-sheet.png <- pickachu/raichu.aseprite
//   cubone-sheet.png <- cubone/cubone.aseprite
//   marowak-sheet.png <- cubone/marowak.aseprite
//   dragonite-sheet.png <- dragonite/dragonite.aseprite
//   mewtwo-sheet.png <- mewtwo/mewtwo.aseprite

export type SpriteSpecies =
  | "squirtle"
  | "wartortle"
  | "blastoise"
  | "bulbasaur"
  | "ivysaur"
  | "venusaur"
  | "charmander"
  | "charmeleon"
  | "charizard"
  | "gastly"
  | "haunter"
  | "munchlax"
  | "snorlax"
  | "jigglypuff"
  | "wigglytuff"
  | "totodile"
  | "croconow"
  | "feraligatr"
  | "pikachu"
  | "raichu"
  | "cubone"
  | "marowak"
  | "dragonite"
  | "mewtwo";

export type SpriteStateName = "idle-left" | "idle-right" | "walking-left" | "walking-right";

export type SpriteFrameRange = { from: number; to: number; flip?: boolean };

export type SpriteSheetEntry = {
  species: SpriteSpecies;
  displayName: string;
  gender: "♂" | "♀";
  sheetUrl: string;
  frameWidth: number;
  frameHeight: number;
  frameCount: number;
  states: Record<SpriteStateName, SpriteFrameRange>;
};

export const SPRITE_SHEETS: Record<SpriteSpecies, SpriteSheetEntry> = {
  squirtle: {
    species: "squirtle",
    displayName: "Squirtle",
    gender: "♂",
    sheetUrl: "/assets/sprites/blastoise/squirtle-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  wartortle: {
    species: "wartortle",
    displayName: "Wartortle",
    gender: "♂",
    sheetUrl: "/assets/sprites/blastoise/wartortle-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  blastoise: {
    species: "blastoise",
    displayName: "Blastoise",
    gender: "♂",
    sheetUrl: "/assets/sprites/blastoise/blastoise-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  bulbasaur: {
    species: "bulbasaur",
    displayName: "Bulbasaur",
    gender: "♂",
    sheetUrl: "/assets/sprites/bulbasaur/bulbasaur-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 10,
    states: {
      "idle-left": { from: 0, to: 0 },
      "idle-right": { from: 1, to: 1 },
      "walking-left": { from: 2, to: 5 },
      "walking-right": { from: 6, to: 9 },
    },
  },
  ivysaur: {
    species: "ivysaur",
    displayName: "Ivysaur",
    gender: "♂",
    sheetUrl: "/assets/sprites/bulbasaur/ivysaur-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 10,
    states: {
      "idle-left": { from: 0, to: 0 },
      "idle-right": { from: 1, to: 1 },
      "walking-left": { from: 2, to: 5 },
      "walking-right": { from: 6, to: 9 },
    },
  },
  venusaur: {
    species: "venusaur",
    displayName: "Venusaur",
    gender: "♂",
    sheetUrl: "/assets/sprites/bulbasaur/venusaur-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 10,
    states: {
      "idle-left": { from: 0, to: 0 },
      "idle-right": { from: 1, to: 1 },
      "walking-left": { from: 6, to: 9 },
      "walking-right": { from: 2, to: 5 },
    },
  },
  charmander: {
    species: "charmander",
    displayName: "Charmander",
    gender: "♂",
    sheetUrl: "/assets/sprites/charizard/charmander-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  charmeleon: {
    species: "charmeleon",
    displayName: "Charmeleon",
    gender: "♂",
    sheetUrl: "/assets/sprites/charizard/charmeleon-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  charizard: {
    species: "charizard",
    displayName: "Charizard",
    gender: "♂",
    sheetUrl: "/assets/sprites/charizard/charizard-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  gastly: {
    species: "gastly",
    displayName: "Gastly",
    gender: "♂",
    sheetUrl: "/assets/sprites/gengar/gastly-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  haunter: {
    species: "haunter",
    displayName: "Haunter",
    gender: "♂",
    sheetUrl: "/assets/sprites/gengar/haunter-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  munchlax: {
    species: "munchlax",
    displayName: "Munchlax",
    gender: "♂",
    sheetUrl: "/assets/sprites/snorlax/munchlax-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  snorlax: {
    species: "snorlax",
    displayName: "Snorlax",
    gender: "♂",
    sheetUrl: "/assets/sprites/snorlax/snorlax-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  jigglypuff: {
    species: "jigglypuff",
    displayName: "Jigglypuff",
    gender: "♂",
    sheetUrl: "/assets/sprites/wigglypuff/jigglypuff-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  wigglytuff: {
    species: "wigglytuff",
    displayName: "Wigglytuff",
    gender: "♂",
    sheetUrl: "/assets/sprites/wigglypuff/wigglytuff-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  totodile: {
    species: "totodile",
    displayName: "Totodile",
    gender: "♂",
    sheetUrl: "/assets/sprites/totodile/totodile-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  croconow: {
    species: "croconow",
    displayName: "Croconaw",
    gender: "♂",
    sheetUrl: "/assets/sprites/totodile/croconow-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  feraligatr: {
    species: "feraligatr",
    displayName: "Feraligatr",
    gender: "♂",
    sheetUrl: "/assets/sprites/totodile/feraligatr-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  pikachu: {
    species: "pikachu",
    displayName: "Pikachu",
    gender: "♂",
    sheetUrl: "/assets/sprites/pickachu/pikachu-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  raichu: {
    species: "raichu",
    displayName: "Raichu",
    gender: "♂",
    sheetUrl: "/assets/sprites/pickachu/raichu-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  cubone: {
    species: "cubone",
    displayName: "Cubone",
    gender: "♂",
    sheetUrl: "/assets/sprites/cubone/cubone-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  marowak: {
    species: "marowak",
    displayName: "Marowak",
    gender: "♂",
    sheetUrl: "/assets/sprites/cubone/marowak-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  dragonite: {
    species: "dragonite",
    displayName: "Dragonite",
    gender: "♂",
    sheetUrl: "/assets/sprites/dragonite/dragonite-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 4,
    states: {
      "idle-left": { from: 0, to: 3, flip: true },
      "idle-right": { from: 0, to: 3 },
      "walking-left": { from: 0, to: 3, flip: true },
      "walking-right": { from: 0, to: 3 },
    },
  },
  mewtwo: {
    species: "mewtwo",
    displayName: "Mewtwo",
    gender: "♂",
    sheetUrl: "/assets/sprites/mewtwo/mewtwo-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 4,
    states: {
      "idle-left": { from: 0, to: 3, flip: true },
      "idle-right": { from: 0, to: 3 },
      "walking-left": { from: 0, to: 3, flip: true },
      "walking-right": { from: 0, to: 3 },
    },
  },
};

export const FIRST_EVOLUTION_BY_COMPANION: Record<CompanionId, SpriteSpecies> = {
  blastoise: "squirtle",
  bulbasaur: "bulbasaur",
  charizard: "charmander",
  gengar: "gastly",
  snorlax: "munchlax",
  wigglypuff: "jigglypuff",
  pikachu: "pikachu",
  totodile: "totodile",
  cubone: "cubone",
  dragonite: "dragonite",
  mewtwo: "mewtwo",
};
