// Generated by scripts/export-sprite-sheets.py — do not edit by hand.
import type { CompanionId } from "@/features/pokeden/companions";

export type SpriteSpecies = "squirtle" | "bulbasaur" | "charmander" | "gastly" | "munchlax" | "jigglypuff" | "totodile" | "pikachu";

export type SpriteStateName = "idle-left" | "idle-right" | "walking-left" | "walking-right";

export type SpriteFrameRange = { from: number; to: number; flip?: boolean };

export type SpriteSheetEntry = {
  species: SpriteSpecies;
  displayName: string;
  gender: "♂" | "♀";
  sheetUrl: string;
  frameWidth: number;
  frameHeight: number;
  frameCount: number;
  states: Record<SpriteStateName, SpriteFrameRange>;
};

export const SPRITE_SHEETS: Record<SpriteSpecies, SpriteSheetEntry> = {
  squirtle: {
    species: "squirtle",
    displayName: "Squirtle",
    gender: "♂",
    sheetUrl: "/assets/sprites/blastoise/squirtle-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  bulbasaur: {
    species: "bulbasaur",
    displayName: "Bulbasaur",
    gender: "♂",
    sheetUrl: "/assets/sprites/bulbasaur/bulbasaur-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 10,
    states: {
      "idle-left": { from: 0, to: 0 },
      "idle-right": { from: 1, to: 1 },
      "walking-left": { from: 2, to: 5 },
      "walking-right": { from: 6, to: 9 },
    },
  },
  charmander: {
    species: "charmander",
    displayName: "Charmander",
    gender: "♂",
    sheetUrl: "/assets/sprites/charizard/charmander-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  gastly: {
    species: "gastly",
    displayName: "Gastly",
    gender: "♂",
    sheetUrl: "/assets/sprites/gengar/gastly-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  munchlax: {
    species: "munchlax",
    displayName: "Munchlax",
    gender: "♂",
    sheetUrl: "/assets/sprites/snorlax/munchlax-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  jigglypuff: {
    species: "jigglypuff",
    displayName: "Jigglypuff",
    gender: "♂",
    sheetUrl: "/assets/sprites/wigglypuff/jigglypuff-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  totodile: {
    species: "totodile",
    displayName: "Totodile",
    gender: "♂",
    sheetUrl: "/assets/sprites/totodile/totodile-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
  pikachu: {
    species: "pikachu",
    displayName: "Pikachu",
    gender: "♂",
    sheetUrl: "/assets/sprites/pickachu/pikachu-sheet.png",
    frameWidth: 28,
    frameHeight: 28,
    frameCount: 5,
    states: {
      "idle-left": { from: 0, to: 0, flip: true },
      "idle-right": { from: 0, to: 0 },
      "walking-left": { from: 1, to: 4, flip: true },
      "walking-right": { from: 1, to: 4 },
    },
  },
};

export const FIRST_EVOLUTION_BY_COMPANION: Record<CompanionId, SpriteSpecies> = {
  blastoise: "squirtle",
  bulbasaur: "bulbasaur",
  charizard: "charmander",
  gengar: "gastly",
  snorlax: "munchlax",
  wigglypuff: "jigglypuff",
  pikachu: "pikachu",
};
